workflows

diff --git a/.github/workflows/prod-pipeline.yaml b/.github/workflows/prod-pipeline.yaml
--- a/.github/workflows/prod-pipeline.yaml
+++ b/.github/workflows/prod-pipeline.yaml
@@ -1,97 +1,104 @@
-# name: PROD Pipeline
+name: PROD Pipeline
 
-# on:
-#   workflow_call:
-#     inputs:
-#       version:
-#         required: true
-#         type: string
-# permissions:
-#   contents: read
-#   statuses: write
+on:
+  workflow_call:
+    inputs:
+      version:
+        required: true
+        type: string
+permissions:
+  contents: read
+  statuses: write
 
-# jobs:
-#   prod-gate:
-#     runs-on: self-hosted
+jobs:
+  prod-gate:
+    runs-on: self-hosted
 
-#     steps:
-#       - name: Compute short commit
-#         id: commit
-#         run: |
-#           SHORT_SHA="${{ inputs.version }}"
-#           APP_VERSION="${SHORT_SHA:0:9}"
+    steps:
+      - name: Compute short commit
+        id: commit
+        run: |
+          SHORT_SHA="${{ inputs.version }}"
+          APP_VERSION="${SHORT_SHA:0:9}"
 
-#           echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
-#           echo "App version: $APP_VERSION"
+          echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
+          echo "App version: $APP_VERSION"
 
-#       - name: Check required commit statuses
-#         id: gate
-#         shell: bash
-#         run: |
-#           echo "🔍 Checking commit statuses for ${{ inputs.version }}"
+      - name: Check required commit statuses
+        id: gate
+        shell: bash
+        run: |
+          echo "🔍 Checking commit statuses for ${{ inputs.version }}"
 
-#           REQUIRED_CONTEXTS=(
-#             "DEV_DEPLOY"
-#             "DOCKER_BUILD"
-#             "UNIT_TESTS"
-#             "SECURITY_CHECK"
-#             "UAT_DEPLOY"
-#           )
+          REQUIRED_CONTEXTS=(
+            "DEV_DEPLOY"
+            "DOCKER_BUILD"
+            "UNIT_TESTS"
+            "SECURITY_CHECK"
+            "UAT_DEPLOY"
+          )
 
-#           RESPONSE=$(curl -s \
-#             -H "Authorization: Bearer ${{ github.token }}" \
-#             -H "Accept: application/vnd.github+json" \
-#             "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.version }}/statuses")
+          RESPONSE=$(curl -s \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.version }}/statuses")
 
-#           FAILED=0
+          FAILED=0
 
-#           for CONTEXT in "${REQUIRED_CONTEXTS[@]}"; do
-#             STATE=$(echo "$RESPONSE" | jq -r \
-#               ".[] | select(.context == \"$CONTEXT\") | .state" | head -n 1)
+          for CONTEXT in "${REQUIRED_CONTEXTS[@]}"; do
+            STATE=$(echo "$RESPONSE" | jq -r \
+              ".[] | select(.context == \"$CONTEXT\") | .state" | head -n 1)
 
-#             if [ -z "$STATE" ]; then
-#               echo "❌ $CONTEXT → status missing"
-#               FAILED=1
-#             elif [ "$STATE" != "success" ]; then
-#               echo "❌ $CONTEXT → $STATE"
-#               FAILED=1
-#             else
-#               echo "✅ $CONTEXT → success"
-#             fi
-#           done
+            if [ -z "$STATE" ]; then
+              echo "❌ $CONTEXT → status missing"
+              FAILED=1
+            elif [ "$STATE" != "success" ]; then
+              echo "❌ $CONTEXT → $STATE"
+              FAILED=1
+            else
+              echo "✅ $CONTEXT → success"
+            fi
+          done
 
-#           if [ "$FAILED" -eq 1 ]; then
-#             echo "🚫 UAT gate failed"
-#             exit 1
-#           fi
+          if [ "$FAILED" -eq 1 ]; then
+            echo "🚫 UAT gate failed"
+            exit 1
+          fi
 
-#           echo "🎉 All required checks passed"
+          echo "🎉 All required checks passed"
 
-#       - name: Configure AWS Credentials
-#         uses: aws-actions/configure-aws-credentials@v5.1.1
-#         with:
-#           aws-region: us-east-1
-#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#       - name: authenticate to EKS
-#         run: |
-#           aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
-#           kubectl get nodes
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v5.1.1
+        with:
+          aws-region: us-east-1
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: authenticate to EKS
+        run: |
+          aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
+          kubectl get nodes
 
-#       - name: checkout catalogue deploy repo
-#         uses: actions/checkout@v6
-#         with:
-#           repository: tallapalemmahicharan/catalogue-deploy
+      - name: checkout catalogue deploy repo
+        uses: actions/checkout@v6
+        with:
+          repository: tallapalemmahicharan/catalogue-deploy
 
-#       - name: deploy to prod cluster
-#         id: prod_deploy
-#         run: "helm upgrade --install catalogue -f values-dev.yaml -n roboshop --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."
+      - name: deploy to prod cluster
+        id: prod_deploy
+        run: |
+          helm upgrade --install catalogue \
+          -f values-dev.yaml \
+          -n roboshop \
+          --set owner.imageversion=${APP_VERSION} \
+          --atomic \
+          --wait \
+          --timeout=5m .
 
-#       - name: Update Deploy status
-#         if: always()
-#         uses: tallapalemmahicharan/workflows/.github/actions/update-commit-status@main
-#         with:
-#           sha: ${{ inputs.version }}
-#           state: ${{ steps.prod_deploy.outcome }}     # success / failure / cancelled
-#           context: PROD_DEPLOY
-#           description: ${{ steps.prod_deploy.outcome }}
+      - name: Update Deploy status
+        if: always()
+        uses: tallapalemmahicharan/workflows/.github/actions/update-commit-status@main
+        with:
+          sha: ${{ inputs.version }}
+          state: ${{ steps.prod_deploy.outcome }}     # success / failure / cancelled
+          context: PROD_DEPLOY
+          description: ${{ steps.prod_deploy.outcome }}
